export const GET_ALL_BLOGS = "GET_ALL_BLOGS";
export const GET_BLOG_BY_CODE = "GET_BLOG_BY_CODE";
export const BLOG_LOADING = "BLOG_LOADING";
export const BLOG_ERROR = "BLOG_ERROR"

export const GET_STYLE_BY_CODE = "GET_STYLE_BY_CODE";
export const GET_ALL_STYLES = "GET_ALL_STYLES";
export const STYLE_LOAD = "STYLE_LOAD";
export const STYLE_ERROR = "STYLE_ERROR";

export const GET_DESIGN_BY_CODE = "GET_DESIGN_BY_CODE";
export const GET_ALL_DESIGNS = "GET_ALL_DESIGNS";
export const DESIGN_LOAD = "DESIGN_LOAD";
export const DESIGN_ERROR = "DESIGN_ERROR";


export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const ADMIN_LOAD = "ADMIN_LOAD";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const SET_ADMIN = "SET_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const LOGIN_WRITER = "LOGIN_WRITER";
export const WRITER_LOAD = "WRITER_LOAD";
export const WRITER_ADD_BLOG_HEAD = "WRITER_ADD_BLOG_HEAD";
export const WRITER_ADD_BLOG_CONTENT = "WRITER_ADD_BLOG_CONTENT";
export const GET_ALL_WRITERS = "GET_ALL_WRITER";
export const WRITER_ERROR = "WRITER_ERROR";
export const LOGOUT_WRITER = "LOGOUT_WRITER";
export const GET_WRITER_BLOGS = "  GET_WRITER_BLOGS";


export const GET_ALL_TL = "GET_ALL_TL";
export const TL_LOAD = "TL_LOAD";
export const TL_ERROR = "TL_ERROR";
export const GET_TL_BY_CODE = "GET_TL_BY_CODE";

export const GET_ALL_CURATORS = "GET_ALL_CURATORS";
export const CURATOR_LOAD = "CURATOR_LOAD";
export const GET_CURATOR_BY_CODE = "GET_CURATOR_BY_CODE";
export const CURATOR_ERROR = "CURATOR_ERROR";
export const CURATOR_LOGIN = "CURATOR_LOGIN";
export const SET_CURATOR = "SET_CURATOR";
export const LOGOUT_CURATOR = "LOGOUT_CURATOR";
export const UPDATE_CURATOR = "UPDATE_CURATOR";
export const GET_CURATOR_STYLES = "GET_CURATOR_STYLES";
export const GET_CURATOR_DESIGNS = "GET_CURATOR_DESIGNS";


export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LIKE_BLOG = "LIKE_BLOG";